spring: 
  application:
    name: wehaul-rental
  cloud:
    stream:
      default-binder: rabbit
      default:
        group: wehaul-rental
      bindings:
        reservationCreated:
          destination: reservation-created-topic
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
