spring:
  application:
    name: wehaul-rental
  cloud:
    function:
      definition: truckAdded;truckInspectionStarted;truckInspectionCompleted
    stream:
      bindings:
        reservationCreated-out-0:
          destination: reservation-created
        reservationStarted-out-0:
          destination: reservation-started
        reservationEnded-out-0:
          destination: reservation-ended
        truckAdded-in-0:
          destination: truck-added
        truckInspectionStarted-in-0:
          destination: truck-inspection-started
        truckInspectionCompleted-in-0:
          destination: truck-inspection-completed

  datasource:
    name: mydb
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: embedded
      platform: h2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG

