apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wehaul-rental
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: wehaul-rental
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: rabbitmq
      ref:
        apiVersion: v1beta1
        kind: RabbitmqCluster
        name: rmq-1
  source:
    git:
      url: https://github.com/sample-accelerators/wehaul-rental
      ref:
        branch: main
