apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wehaul-rental
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: wehaul-rental
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
#    - name: db
#      ref:
#        apiVersion: sql.tanzu.vmware.com/v1
#        kind: Postgres
#        name: postgres-tap-hack-1
#        namespace: default
    - name: rabbitmq
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: rmq-1
  source:
    git:
      url: https://github.com/tyslasvmw/wehaul-rental
      ref:
        branch: main
