CREATE TABLE if not exists RESERVATION
(
    ID                  INT GENERATED ALWAYS AS IDENTITY,
    TRUCK_ID            INT,
    RESERVATION_STATUS  VARCHAR(100),
    CONSTRAINT RESERVATION_ID_PK PRIMARY KEY (ID)
);